# -*- coding: utf-8 -*-
"""Web-Scraping-Thanakorn-Pasangthien-6088109.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18GMXY3TVTs1BQq8wkkjR-8VewG2qB3CF

# Web Scraping using Beautiful Soup

Importing Modules
"""

!pip install --upgrade pip
!pip install requests
!pip install beautifulsoup4
!pip install pandas

#Thanakorn Pasangthien 6088109
import requests
import bs4
import pandas as pd

#load the Movie website

response = requests.get("https://www.imdb.com/search/title/?genres=comedy&groups=top_250&sort=user_rating,desc")

#create the soup
soup = bs4.BeautifulSoup(response.text,"html.parser")

#extract data that we need
movie_name = soup.select('.lister-item-header a')
genre = soup.select(".text-muted .genre")
description = soup.select("div.ratings-bar ~ p.text-muted")
rating = soup.select("div.ratings-imdb-rating > strong")
time = soup.select('span.runtime')

#clean html tag out and get only text 
def cleanData(data):
    new_data = []
    for i in data:
        new_data.append(i.text)
    return new_data

#final clean data text
clean_movie_name = cleanData(movie_name)
clean_genre = cleanData(genre)
clean_description = cleanData(description)
clean_rating = cleanData(rating)
clean_time = cleanData(time)

data = {
    'Movie_name':clean_movie_name,
    'Genre':clean_genre,
    'Description':clean_description,
    'Rating':clean_rating,
    'Run_Time':clean_time
}

#create data frame from existing data
df = pd.DataFrame(data,columns=['Movie_name','Genre','Description','Rating','Run_Time'])

#write file into desired format
df.to_csv("Movie_Data_Result.csv")
df.to_excel("Movie_Data_Result.xlsx")
df.to_json("Movie_Data_Result.json")